#include <Utils/EnumToStrKeyMapping.h>
#include "MCM/MCM_INI_KeyMapping.h"


namespace CustomCamera::MCM {
    STR_KEY_ARRAY_INITIALIZER(MCMKeys, _SectionNames, SECTION_NAMES(MAP_STRS))
    STR_KEY_ARRAY_INITIALIZER(MCMKeys, Main, KEY_IDS_MAIN(MAP_STRS))
    STR_KEY_ARRAY_INITIALIZER_FROM_SECTION(MCMKeys, Camera, Offsets, KEY_IDS_OFFSETS(MAP_STRS))
    STR_KEY_ARRAY_INITIALIZER_FROM_SECTION(MCMKeys, Camera, Misc, KEY_IDS_MISC(MAP_STRS))
    STR_KEY_ARRAY_INITIALIZER_FROM_SECTION(MCMKeys, Camera, Global, KEY_IDS_GLOBAL(MAP_STRS))
}